/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rlcfzBRnjVK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardContent, CardDescription} from "components/ui/card"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "components/ui/select"
import { CartesianGrid, XAxis, Bar, BarChart, Line, LineChart, Area, AreaChart } from "recharts"
import { ChartTooltipContent, ChartTooltip, ChartContainer } from "components/ui/chart"
import { Footer } from "./footer"

export function APIUsage() {
  const [timeUnit, setTimeUnit] = useState("hour")
  const apiUsageData = {
  }
  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-b from-purple-100 to-purple-200">
      <div className="flex-1 flex">
        <aside className="bg-white border-r p-6 space-y-6">
          <h2 className="text-lg font-bold text-purple-800">My Page</h2>
          <nav className="space-y-4">
            <div>
              <h3 className="text-sm font-semibold text-gray-700">API Usage</h3>
              <ul className="space-y-2 ml-4">
                <li>
                  <Link href="#" className="text-sm text-gray-600 hover:text-purple-800" prefetch={false}>
                    Statistics
                  </Link>
                </li>
                <li>
                  <Link href="#" className="text-sm text-gray-600 hover:text-purple-800" prefetch={false}>
                    Real-time
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-sm font-semibold text-gray-700">Profile</h3>
              <ul className="space-y-2 ml-4">
                <li>
                  <Link href="/profile" className="text-sm text-gray-600 hover:text-purple-800" prefetch={false}>
                    Profile
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-sm font-semibold text-gray-700">Documentation</h3>
              <ul className="space-y-2 ml-4">
                <li>
                  <Link href="#" className="text-sm text-gray-600 hover:text-purple-800" prefetch={false}>
                    Swagger
                  </Link>
                </li>
              </ul>
            </div>
          </nav>
        </aside>
        <main className="flex-1 flex flex-col items-stretch justify-center text-center mx-auto max-w-2xl">
          <div className="grid gap-6">
            <Card>
              <CardHeader>
                <CardTitle>API Usage Statistics</CardTitle>
                <CardDescription>View your daily, monthly, and hourly API usage statistics.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-3 gap-4">
                  <div className="flex flex-col items-center gap-1">
                    <div className="text-4xl font-bold">1,234</div>
                    <div className="text-sm text-muted-foreground">Daily</div>
                  </div>
                  <div className="flex flex-col items-center gap-1">
                    <div className="text-4xl font-bold">35,678</div>
                    <div className="text-sm text-muted-foreground">Monthly</div>
                  </div>
                  <div className="flex flex-col items-center gap-1">
                    <div className="text-4xl font-bold">156</div>
                    <div className="text-sm text-muted-foreground">Hourly</div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>API Limit Information</CardTitle>
                <CardDescription>Check your current API limit and usage.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="flex items-center justify-between">
                    <div>API Limit</div>
                    <div className="font-medium">50,000 requests/month</div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>API Usage</div>
                    <div className="font-medium">35,678 requests</div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>Remaining Requests</div>
                    <div className="font-medium">14,322 requests</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </main>
        <main className="flex-1 flex flex-col items-stretch justify-center text-center mx-auto max-w-5xl">
          <div className="grid gap-6">
            <Card>
              <CardHeader>
                <CardTitle>API Usage Statistics</CardTitle>
                <CardDescription>View your daily, monthly, and hourly API usage statistics.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-3 gap-4">
                  <div className="flex flex-col items-center gap-1">
                    <div className="text-4xl font-bold">1,234</div>
                    <div className="text-sm text-muted-foreground">Daily</div>
                  </div>
                  <div className="flex flex-col items-center gap-1">
                    <div className="text-4xl font-bold">35,678</div>
                    <div className="text-sm text-muted-foreground">Monthly</div>
                  </div>
                  <div className="flex flex-col items-center gap-1">
                    <div className="text-4xl font-bold">156</div>
                    <div className="text-sm text-muted-foreground">Hourly</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </main>
      </div>
      <Footer />
    </div>
  )
}

function AreachartChart(props) {
  return (
    <div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}
        className="min-h-[300px]"
      >
        <AreaChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
          margin={{
            left: 12,
            right: 12,
          }}
        >
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            axisLine={false}
            tickMargin={8}
            tickFormatter={(value) => value.slice(0, 3)}
          />
          <ChartTooltip cursor={false} content={<ChartTooltipContent indicator="line" />} />
          <Area
            dataKey="desktop"
            type="natural"
            fill="var(--color-desktop)"
            fillOpacity={0.4}
            stroke="var(--color-desktop)"
          />
        </AreaChart>
      </ChartContainer>
    </div>
  )
}


function BarchartChart(props) {
  return (
    <div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}
        className="min-h-[300px]"
      >
        <BarChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
        >
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            tickMargin={10}
            axisLine={false}
            tickFormatter={(value) => value.slice(0, 3)}
          />
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Bar dataKey="desktop" fill="var(--color-desktop)" radius={8} />
        </BarChart>
      </ChartContainer>
    </div>
  )
}


function LinechartChart(props) {
  return (
    <div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}
      >
        <LineChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
          margin={{
            left: 12,
            right: 12,
          }}
        >
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            axisLine={false}
            tickMargin={8}
            tickFormatter={(value) => value.slice(0, 3)}
          />
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Line dataKey="desktop" type="natural" stroke="var(--color-desktop)" strokeWidth={2} dot={false} />
        </LineChart>
      </ChartContainer>
    </div>
  )
}
