/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XUDmYFkuZk5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

'use client';

import { Button } from "components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "components/ui/card"
import { Label } from "components/ui/label"
import { Input } from "components/ui/input"
import Link from "next/link"
import { useRouter } from "next/navigation";
import { MainFooter } from "./footer";



export function Login() {
  const router = useRouter()
  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-b from-purple-100 to-purple-200">
      <header className="flex items-center justify-between p-6">
        <Link href="/" className="text-2xl font-bold text-purple-800" prefetch={false}>
          OaaSIS ROUTING ENGINE
        </Link>        
        <nav className="flex items-center space-x-6">
          <a href="#" className="text-sm text-gray-700">
            Documentation
          </a>
          <a href="#" className="text-sm text-gray-700">
            Company
          </a>
          <Button variant="outline">Log In</Button>
        </nav>
      </header>
      <main className="flex flex-col items-center justify-center flex-1 px-6 py-12 text-center">
        <div className="w-full max-w-md">
          <Card>
            <CardHeader>
              <CardTitle>Login</CardTitle>
              <CardDescription>Enter your email and password to access your account.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 gap-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" placeholder="m@example.com" />
              </div>
              <div className="grid grid-cols-1 gap-2">
                <Label htmlFor="password">Password</Label>
                <Input id="password" type="password" />
              </div>
            </CardContent>
            <CardFooter className="flex items-center justify-between">
              <Link href="#" className="text-sm text-gray-600 hover:underline" prefetch={false}>
                Forgot password?
              </Link>
              <Button type="submit" className="w-full">
                Login
              </Button>
            </CardFooter>
          </Card>
          <div className="mt-4 text-center text-sm text-gray-600">
            Don't have an account?{" "}
            <Link href="/signup" className="font-medium text-purple-600 hover:underline" prefetch={false}>
              Sign up
            </Link>
          </div>
        </div>
      </main>
      <MainFooter />
    </div>
  )
}
