/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vU2kVPwEIWG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

'use client';

import { Button } from "components/ui/button"
import { Input } from "components/ui/input"
import { useRouter } from 'next/navigation'
import { MainFooter } from "./footer";

export function Main() {
  const router = useRouter()
  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-b from-purple-100 to-purple-200">
      <header className="flex items-center justify-between p-6">
        <h1 className="text-2xl font-bold text-purple-800">OaaSIS ROUTING ENGINE</h1>
        <nav className="flex items-center space-x-6">
          <a href="#" className="text-sm text-gray-700">
            Documentation
          </a>
          <a href="#" className="text-sm text-gray-700">
            Company
          </a>
          <Button variant="outline" onClick={()=> router.push("/login")} >Log In</Button>
        </nav>
      </header>
      <main className="flex flex-col items-center justify-center flex-1 px-6 py-12 text-center">
        <h2 className="text-4xl font-bold text-gray-900">AI-Powered Route Optimization API</h2>
        <p className="mt-4 text-lg text-gray-700">
          SUPERCHARGE YOUR LOGISTICS WITH LIGHTNING-FAST, HIGH-PERFORMANCE ROUTING SOLUTIONS
        </p>
        <p className="mt-4 text-gray-600">
          Our advanced AI-based solver delivers unparalleled efficiency for middle-mile logistics, last-mile deliveries,
          food delivery, and quick commerce. Transform your delivery operations and elevate your business performance
          with our cutting-edge technology.
        </p>
        <div className="relative mt-8">
          <SearchIcon className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
          <Input
            type="search"
            placeholder="Have a question? Ask or enter a search term"
            className="pl-10 pr-4 py-2 w-full max-w-lg border rounded-md"
          />
        </div>
        <div className="grid grid-cols-1 gap-8 mt-12 md:grid-cols-2 lg:grid-cols-4">
          <div className="flex flex-col items-center">
            <FileIcon className="h-12 w-12 text-purple-600" />
            <h3 className="mt-4 text-lg font-semibold text-gray-900">API Documentation</h3>
            <p className="mt-2 text-sm text-gray-600">
              Proin dictum lobortis justo at pretium. Nunc malesuada ante sit amet purus ornare pulvinar.
            </p>
            <a href="#" className="mt-2 text-sm text-purple-600">
              →
            </a>
          </div>
          <div className="flex flex-col items-center">
            <FolderIcon className="h-12 w-12 text-purple-600" />
            <h3 className="mt-4 text-lg font-semibold text-gray-900">Community Forum</h3>
            <p className="mt-2 text-sm text-gray-600">
              Proin dictum lobortis justo at pretium. Nunc malesuada ante sit amet purus ornare pulvinar.
            </p>
            <a href="#" className="mt-2 text-sm text-purple-600">
              →
            </a>
          </div>
          <div className="flex flex-col items-center">
            <FileIcon className="h-12 w-12 text-purple-600" />
            <h3 className="mt-4 text-lg font-semibold text-gray-900">FAQ</h3>
            <p className="mt-2 text-sm text-gray-600">
              Proin dictum lobortis justo at pretium. Nunc malesuada ante sit amet purus ornare pulvinar.
            </p>
            <a href="#" className="mt-2 text-sm text-purple-600">
              →
            </a>
          </div>
          <div className="flex flex-col items-center">
            <SettingsIcon className="h-12 w-12 text-purple-600" />
            <h3 className="mt-4 text-lg font-semibold text-gray-900">Community Forum</h3>
            <p className="mt-2 text-sm text-gray-600">
              Proin dictum lobortis justo at pretium. Nunc malesuada ante sit amet purus ornare pulvinar.
            </p>
            <a href="#" className="mt-2 text-sm text-purple-600">
              →
            </a>
          </div>
        </div>
      </main>
      <MainFooter />
    </div>
  )
}

function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  )
}


function FolderIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function SettingsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
