/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rlcfzBRnjVK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardContent, CardDescription} from "components/ui/card"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "components/ui/select"
import { CartesianGrid, XAxis, Bar, BarChart, Line, LineChart, Area, AreaChart } from "recharts"
import { ChartTooltipContent, ChartTooltip, ChartContainer } from "components/ui/chart"
import { Footer } from "./footer"

export function Profile() {
  const [timeUnit, setTimeUnit] = useState("hour")
  const apiUsageData = {
  }
  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-b from-purple-100 to-purple-200">
      <div className="flex-1 flex">
        <aside className="bg-white border-r p-6 space-y-6">
          <h2 className="text-lg font-bold text-purple-800">My Page</h2>
          <nav className="space-y-4">
            <div>
              <h3 className="text-sm font-semibold text-gray-700">API Usage</h3>
              <ul className="space-y-2 ml-4">
                <li>
                  <Link href="/statistics" className="text-sm text-gray-600 hover:text-purple-800" prefetch={false}>
                    Statistics
                  </Link>
                </li>
                <li>
                  <Link href="/real-time" className="text-sm text-gray-600 hover:text-purple-800" prefetch={false}>
                    Real-time
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-sm font-semibold text-gray-700">Profile</h3>
              <ul className="space-y-2 ml-4">
                <li>
                  <Link href="/profile" className="text-sm text-gray-600 hover:text-purple-800" prefetch={false}>
                    Profile
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-sm font-semibold text-gray-700">Documentation</h3>
              <ul className="space-y-2 ml-4">
                <li>
                  <Link href="#" className="text-sm text-gray-600 hover:text-purple-800" prefetch={false}>
                    Swagger
                  </Link>
                </li>
              </ul>
            </div>
          </nav>
        </aside>
        <main className="flex-1 flex flex-col items-stretch justify-center text-center mx-auto max-w-3xl">
          <div className="grid gap-6">
            <Card>
              <CardHeader>
                <CardTitle>Profile</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <div>Email</div>
                  <div className="font-medium">
                    <code>larry@omelet.ai</code>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <div>password</div>
                  <div className="font-medium">
                    <code>oaasis***</code>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <div>signout</div>
                  <div className="font-medium">
                    <code>oaasis***</code>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Your App Key</CardTitle>
                <CardDescription>This is your unique API key for accessing the OaaSIS API.</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <div>App Key</div>
                  <div className="font-medium">
                    <code>abc123def456ghi789</code>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <div>App Test</div>
                  <div className="font-medium">
                    <code>Sucess</code>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </main>
      </div>
      <Footer />
    </div>
  )
}