/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7w8a9hWrrUL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
'use client';
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "components/ui/card"
import { Label } from "components/ui/label"
import { Input } from "components/ui/input"
import { Button } from "components/ui/button"
import { MainFooter } from "./footer";

export function Signup() {
  return (
    <div className="flex flex-col min-h-screen bg-gradient-to-b from-purple-100 to-purple-200">
      <header className="flex items-center justify-between p-6">
        <Link href="/" className="text-2xl font-bold text-purple-800" prefetch={false}>
          OaaSIS ROUTING ENGINE
        </Link>
        <nav className="flex items-center space-x-6">
          <a href="#" className="text-sm text-gray-700">
            Documentation
          </a>
          <a href="#" className="text-sm text-gray-700">
            Company
          </a>
          <Link href="#" className="text-sm text-gray-700" prefetch={false}>
            Log In
          </Link>
        </nav>
      </header>
      <main className="flex flex-col items-center justify-center flex-1 px-6 py-12 text-center">
        <div className="w-full max-w-md">
          <Card>
            <CardHeader>
              <CardTitle>Sign Up</CardTitle>
              <CardDescription>Enter your details to create a new account.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-1 gap-2">
                <Label htmlFor="name">Name</Label>
                <Input id="name" type="text" placeholder="John Doe" />
              </div>
              <div className="grid grid-cols-1 gap-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" type="email" placeholder="m@example.com" />
              </div>
              <div className="grid grid-cols-1 gap-2">
                <Label htmlFor="password">Password</Label>
                <Input id="password" type="password" />
              </div>
              <div className="grid grid-cols-1 gap-2">
                <Label htmlFor="confirmPassword">Confirm Password</Label>
                <Input id="confirmPassword" type="password" />
              </div>
            </CardContent>
            <CardFooter className="flex items-center justify-between">
              <Button type="submit" className="w-full">
                Sign Up
              </Button>
            </CardFooter>
          </Card>
          <div className="mt-4 text-center text-sm text-gray-600">
            Already have an account?{" "}
            <Link href="#" className="font-medium text-purple-600 hover:underline" prefetch={false}>
              Log In
            </Link>
          </div>
        </div>
      </main>
      <MainFooter />
    </div>
  )
}
